x-common-env: &common-env
  CMD_DOMAIN: localhost:${CMD_PORT:-8080}
services:
  reverse-proxy:
    image: caddy:2.9-alpine
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
    - "${CMD_PORT:-8080}:80"
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: hedgedoc
      POSTGRES_USER: hedgedoc
      POSTGRES_PASSWORD: password
    volumes:
    - db:/var/lib/postgresql/data
    restart: always
  # do not change the app service name as it is hard-wired
  # into renderknecht; this way, we don't have to implement
  # any service discovery
  app:
    image: quay.io/hedgedoc/hedgedoc:1.10.2
    environment:
      !!merge <<: *common-env
      CMD_PORT: 3000  # do not change; renderknecht has this port hard-coded
      CMD_DB_URL: postgres://hedgedoc:password@database:5432/hedgedoc
      CMD_URL_ADDPORT: false
      CMD_PROTOCOL_USESSL: false
    volumes:
    - uploads:/hedgedoc/public/uploads
    restart: always
    depends_on:
    - database
  # do not change the plantuml service name as it is hard-wired
  # into renderknecht; this way, we don't have to implement
  # any service discovery
  plantuml:
    image: plantuml/plantuml-server:jetty-v1.2025.0
    restart: always
  renderknecht:
    image: renderknecht:latest
    build:
      context: .
      dockerfile: Dockerfile.renderknecht
    environment:
      !!merge <<: *common-env
      PREAMBLE_YAML: preamble.yaml
      AUTHORS_YAML: authors.yaml

volumes:
  db:
  uploads:
